Change Tue Apr  7 22:38:53 CEST 2015

diff --git a/run b/run
--- a/run
+++ b/run
@@ -4,7 +4,7 @@
 #####################################################################
 
 # Environment variables and their defaults
-LOG_LEVEL="${LOG_LEVEL:-7}" # 7 = debug -> 0 = emergency
+LOG_LEVEL="${LOG_LEVEL:-5}" # 7 = debug -> 0 = emergency
 
 # Commandline options. This defines the usage page, and is used to parse cli
 # opts & defaults from. The parsing is unforgiving so be precise in your syntax
@@ -17,6 +17,7 @@ INITDIR="$(readlink --canonicalize "$(dirname "$0")")"
 REQUIREMENTS="/sbin/ip /usr/bin/slirp-fullbolt $INITDIR/uml"
 CMD="true"
 LOGDIR="/tmp/log.$$"
+PIDS=()
 
 ### Functions
 #####################################################################
@@ -63,10 +64,12 @@ help() {
 
 cleanup_before_exit() {
   # print contents of all logdir files
-  find "$LOGDIR" -maxdepth 1 -type f -exec echo -e "\nDisplaying contents of {}\n=========================================" \; -exec cat {} \;
+  [ "${LOG_LEVEL}" -ge 7 ] && find "$LOGDIR" -maxdepth 1 -type f -exec echo -e "\nDisplaying contents of {}\n=========================================" \; -exec cat {} \;
   # remove the temporary log directory
   debug "Deleting $LOGDIR"
   rm -rf "$LOGDIR" 2> /dev/null
+  # killing auxilary processes
+  kill "$@"
 }
 trap cleanup_before_exit EXIT
 
@@ -164,34 +167,43 @@ CMD="${*}"
 ### Runtime
 #####################################################################
 
-# LOGDIR=/tmp/log.$$
-# mkdir $LOGDIR
+# Exit on error. Append ||true if you expect an error.
+# set -e is safer than #!/bin/bash -e because that is neutralised if
+# someone runs your script like `bash yourscript.sh`
+# set -o errexit
+# set -o nounset
 
-if [ "$1" ]
-then
-	# CMD="$*"
-	STDIN=/dev/null
-	STDOUT=/dev/null
-	STDERR=/dev/null
-	touch $LOGDIR/output
-	if [ "$VERBOSE" = 1 ]; then
-		tail -f $LOGDIR/output &
-	fi
-	TAILPID=$!
-	trap '' TERM
-else
-	CMD=/bin/bash
-	STDIN=/dev/stdin
-	STDOUT=/dev/stdout
-	STDERR=/dev/stderr
-	TAILPID=""
-fi
+# Bash will remember & return the highest exitcode in a chain of pipes.
+# This way you can catch the error in case mysqldump fails in `mysqldump |gzip`
+# set -o pipefail
 
 # Setup logging directory and files
 debug "Preparing log directory: ${LOGDIR}"
 mkdir -p "${LOGDIR}"
 cp "/etc/resolv.conf" "${LOGDIR}/resolv.conf"
 echo "${CMD}" > "${LOGDIR}/cmd"
+
+if [ "$1" ]; then
+	STDIN=/dev/null
+	STDOUT=/dev/null
+	STDERR=/dev/null
+	touch $LOGDIR/stdout
+	touch $LOGDIR/stderr
+	# if [ "$VERBOSE" = 1 ]; then
+	tail -f $LOGDIR/stdout &
+	PIDS+=($!)
+	tail -f $LOGDIR/stderr &
+	PIDS+=($!)
+	# fi
+	# TAILPID=$!
+	# trap '' TERM
+else
+	# CMD=/bin/bash
+	STDIN=/dev/stdin
+	STDOUT=/dev/stdout
+	STDERR=/dev/stderr
+	TAILPID=""
+fi
 
 # Execute `$CMD` in User-Mode Linux
 debug "Going to execute command: ${CMD}"
@@ -202,7 +214,7 @@ INITDIR="$(readlink --canonicalize "$(dirname "$0")")"
 	eth0="slirp,,$INITDIR/slirp-wrapper" \
 	init="$INITDIR/init ${CMD}" \
 	TERM="$TERM" LOGDIR="$LOGDIR"
-	# <"$STDIN" >"$STDOUT" 2>"$STDERR"
+	<"$STDIN" >"$STDOUT" 2>"$STDERR"
 
 # Due to a weird behavior of usermodelinux, sometimes it will kill the
 # whole process group, and we won't have to kill tail. Duh.
diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,12 +1,11 @@
 #!/bin/bash
 
 REQUIREMENTS="/usr/bin/shunit2 /bin/nc"
-for R in $REQUIREMENTS
-do
-	[ -x $R ] || {
-		echo "Requirement $R not found. Aborting."
-		exit 1
-	}
+for R in $REQUIREMENTS; do
+    if [ ! -x "$R" ]; then
+        echo "Checking requirement $R... Not found. Aborting"
+        exit 1
+    fi
 done
 
 handleSigTerm()
@@ -21,7 +20,7 @@ oneTimeSetUp()
 
 testSlirpRedirNeedsHostIp()
 {
-    HOST_IP='' SLIRP_PORTS=12345 ./run "true"
+    HOST_IP='' SLIRP_PORTS=12345 ./run -d "true"
 
     assertNotEquals "Providing SLIRP_PORTS should require HOST_IP" 0 $?
 }
@@ -33,7 +32,7 @@ testGuestReachableViaSlirp()
         grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')
     port=12345
 
-    HOST_IP="$host_ip" SLIRP_PORTS=$port ./run "nc -l $port" &
+    HOST_IP="$host_ip" SLIRP_PORTS=$port ./run -d "nc -l $port" &
     UML_PID=$!
 
     # give uml a little time to start
@@ -48,28 +47,28 @@ testGuestReachableViaSlirp()
 
 test_true()
 {
-    ./run "true"
+    ./run -d true
     local exit_code="$?"
     assertEquals "Should exit with code 0" 0 $exit_code
 }
 
 test_false()
 {
-    ./run "false"
+    ./run -d false
     local exit_code="$?"
     assertEquals "Should exit with code 1" 1 $exit_code
 }
 
 test_exit_2()
 {
-    ./run "exit 2"
+    ./run -d exit 2
     local exit_code="$?"
     assertEquals "Should exit with code 2" 2 $exit_code
 }
 
 test_exit_25()
 {
-    ./run exit 25
+    ./run -d exit 25
     local exit_code="$?"
     assertEquals "Should exit with code 25" 25 $exit_code
 }
